---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: regionalmap
  namespace: regionalmap
spec:
  interval: 5m
  chart:
    spec:
      chart: regionalmap
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: codefresh
        namespace: flux-system
  values:
    image:
      repository: bjornmagnusson/regionalmap
      tag: 8b290932fd2d94ace8ff13004fea7fd8265d57c7
