---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: regionalmap
  namespace: regionalmap
spec:
  interval: 5m
  chart:
    spec:
      chart: regionalmap
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: codefresh
        namespace: flux-system
  values:
    image:
      repository: bjornmagnusson/regionalmap
      tag: fbd48c70148a550136079f82764422c29c38da3c
