---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: express-demo
  namespace: express-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: express-demo
      version: v0.2.0
      sourceRef:
        kind: HelmRepository
        name: codefresh
        namespace: flux-system
  values:
    image:
      repository: bjornmagnusson/express-demo
      tag: 99e2a997dd679f6156d1a5a7d82c54d34f778afe
    ingress:
      enabled: true
