---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  channel: gitops
  type: discord
  username: flux
  secretRef:
    name: discord
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: discord
  namespace: flux-system
spec:
  eventSeverity: error
  eventSources:
  - kind: Kustomization
    name: flux-system
  providerRef:
    name: discord
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: express-demo
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    namespace: express-demo
    name: express-demo
  providerRef:
    name: discord
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: regionalmap
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    namespace: regionalmap
    name: regionalmap
  providerRef:
    name: discord